name: 'CICD'
on: 
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Vulnerability Check'
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.14'
          check-latest: true

      - name: 'Unit Test'
        run: |
          go test hello-world_test.go
      
      - name: 'Run test'
        run : |
          go run hello-world.go
          
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check Previous Job Status'
    #    if: success()
        
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arturgrigoryan1/lesson_task_19.05:latest
      
      
      
  










  
