name: 'CICD'
on: 
  workflow_dispatch:
  
jobs:
  build_and_test:
    name: 'Run Native CLI'
    uses: ArturGrigoryan1/lesson_task_19.05/.github/workflows/build_run_tests.yml@main
          
  docker_build_push:
    if: success()
    name: 'Run Docker'
    needs:
      - build_and_test
    uses: ArturGrigoryan1/lesson_task_19.05/.github/workflows/docker_build_push.yml@main
    secrets: inherit
    
