name: 'CICD'
on: 
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Vulnerability Check'
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.14'
          check-latest: true

      - name: 'Unit Test'
        working-directory: 'reverse'
        run: |
          go test .
  
